[tool.poetry]
name = "binance-expert"
version = "0.1.0"
description = "Application for Binance expert"
authors = ["Oleg Alexandrov <alexandrovoleg.ru@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.6"
python-dotenv-vault = "^0.6.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
