[project]
name = "expert"
version = "0.1.0"
description = "Expert application"
authors = [{ name = "Oleg Alexandrov", email = "alexandrovoleg.ru@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "uv>=0.6.2",
]

[project.scripts]
#bot-ema = "examples/src/bot_ema:main"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "python-dotenv-vault>=0.6.4",
]
lint = [
  "ruff>=0.9.5"
]
test = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
]
docs = [
    "sphinx>=4.3.0",
]

[tool.uv]
package = true
link-mode = "copy"
default-groups = [
    "test",
	"lint",
    "docs",
]

[tool.uv.sources]
#expert = { path = "expert" }
binance = { path = "binance" }

[tool.uv.workspace]
members = [
    #"expert",
    "app",
    "binance",
    "examples",
]
exclude = [
    "tests",
    "rust",
    "typescript",
]

[tool.ruff]
line-length = 99
src = [
    "src",
    "app/src",
    "binance/src",
    "examples/**/src",
    "tests",
]
