[project]
name = "binance-expert"
version = "0.1.0"
description = "Application for Binance expert"
authors = [{ name = "Oleg Alexandrov", email = "alexandrovoleg.ru@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    #"binance-connector>=3.12.0",
    #"numpy>=2.2.2",
	#"pandas>=2.2.3",
    #"ta-lib",
	"numpy; python_version >= '3.11'",
	"pandas; python_version >= '3.11'",
    "uv>=0.6.2",
]

[project.scripts]
bot-ema = "bot_ema/src:main"
dotenv-pull = "npx dotenv-vault@latest pull"
dotenv-push = "npx dotenv-vault@latest push"
clean-cache = "poetry cache clear pypi --all && poetry cache clear _default_cache --all"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "python-dotenv-vault>=0.6.4",
]
lint = [
  "ruff>=0.9.5"
]
test = [
    "pytest>=8.3.4",
]
docs = [
    "sphinx>=4.3.0",
]

[tool.uv]
package = true
link-mode = "copy"
default-groups = [
    "test",
	"lint",
    "docs",
]

[tool.uv.sources]
expert = { path = "python/expert" }
binance = { path = "python/binance" }

[tool.uv.workspace]
members = [
    "python/app",
    "python/expert",
    "python/binance",
    "python/examples/bot_ema",
]
exclude = ["python/tests"]


[tool.ruff]
#line-length = 99
src = ["python"]
