[package]
name = "rust"
version = "0.1.0"
edition = "2021"
authors = ["Oleg Alexandrov <alexandrovoleg.ru@gmail.com>"]

[dependencies]
dotenv-vault = "0.1.2"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.43.0", features = ["full"] }
