[project]
name = "binance-expert"
version = "0.1.0"
description = "Application for Binance expert"
authors = [{ name = "Oleg Alexandrov", email = "alexandrovoleg.ru@gmail.com" }]
requires-python = "~=3.11"
readme = "README.md"
dependencies = [
    "binance-connector>=3.8.1,<4",
    "pandas>=2.2.2,<3",
    "numpy>=2.0.1,<3",
    "flask>=3.0.3,<4",
    "ta-lib",
]

[project.scripts]
dotenv-pull = "npx dotenv-vault@latest pull"
dotenv-push = "npx dotenv-vault@latest push"
flask-run = "flask --app src/app run"
clean-cache = "poetry cache clear pypi --all && poetry cache clear _default_cache --all"

[dependency-groups]
dev = [
    "setuptools>=72.1.0,<73",
    "ruff>=0.5.6,<0.6",
    "python-dotenv-vault>=0.6.4,<0.7",
]
test = ["pytest>=8.3.2,<9"]

[tool.uv]
package = false
default-groups = [
    "dev",
    "test",
]

[tool.uv.sources]
ta-lib = [
    { url = "https://github.com/cgohlke/talib-build/releases/download/v0.4.29/TA_Lib-0.4.29-cp311-cp311-win_amd64.whl", marker = "sys_platform == 'win64'" },
    { index = "pypi", marker = "sys_platform == 'linux'" },
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 99
src = ["src"]
