[project]
name = "expert"
version = "0.1.0"
description = "Binance expert"
authors = [{ name = "Oleg Alexandrov", email = "alexandrovoleg.ru@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[project.scripts]


[tool.uv.sources]


[tool.uv.workspace]
